[[d1_databases]]
binding = "FEED_DB"
database_name = "shop-dawg-microfeed_feed_db_development"

[env.preview.d1_databases]
binding = "FEED_DB"
database_name = "shop-dawg-microfeed_feed_db_preview"

[env.production.d1_databases]
binding = "FEED_DB"
database_name = "shop-dawg-microfeed_feed_db_production"
