name = "microfeed"
compatibility_date = "2024-03-03"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "microfeed-media"
preview_bucket_name = "microfeed-media-preview"

