[[d1_databases]]
binding = "FEED_DB"
database_name = "shop-dawg-microfeed_feed_db_development"
database_id = ""

[[env.production.d1_databases]]
binding = "FEED_DB"
database_name = "shop-dawg-microfeed_feed_db_production"
database_id = ""

[[env.preview.d1_databases]]
binding = "FEED_DB"
database_name = "shop-dawg-microfeed_feed_db_preview"

[site]
bucket = "./dist"
entry-point = "functions/index.jsx"
