name = "microfeed"
compatibility_date = "2024-03-03"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "microfeed-media"
preview_bucket_name = "microfeed-media-preview"

[[d1_databases]]
binding = "FEED_DB"
database_name = "shop-dawg-microfeed_feed_db_development_development"
database_id = "f73ddd4c-a748-426c-8be9-2bf08b2c33f5"

[[env.production.d1_databases]]
binding = "FEED_DB"
database_name = "shop-dawg-microfeed_feed_db_production_production"
database_id = "67c53614-394b-4475-b30d-1baec3c5dcd8"

[[env.preview.d1_databases]]
binding = "FEED_DB"
database_name = "shop-dawg-microfeed_feed_db_preview_preview"
database_id = "6e5ba262-e767-401b-bc88-6189ab7b70d9"
