name = "microfeed"
compatibility_date = "2024-03-03"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "microfeed-media"
preview_bucket_name = "microfeed-media-preview"

[[env.preview.d1_databases]]
binding = "FEED_DB"
database_name = "shop-dawg-microfeed_feed_db_preview"
database_id = "84edb8bb-eef5-495c-a0d6-91681a278bcf"